// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkji1E2EDyL6AB4BDnyJkQMZgtA2YfSjo',
    appId: '1:976150402435:web:4bbaa0e4d35195436512b6',
    messagingSenderId: '976150402435',
    projectId: 'invoicegeneratordatabase-fdd48',
    authDomain: 'invoicegeneratordatabase-fdd48.firebaseapp.com',
    storageBucket: 'invoicegeneratordatabase-fdd48.appspot.com',
    measurementId: 'G-56188EMZ4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuPd9F6hroavK5p_XPmwWNaDpTH9C4Eao',
    appId: '1:976150402435:android:db9f7e224a9d80b96512b6',
    messagingSenderId: '976150402435',
    projectId: 'invoicegeneratordatabase-fdd48',
    storageBucket: 'invoicegeneratordatabase-fdd48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkxKMozOmASOXI6bC3sRon19wpxLTpFw4',
    appId: '1:976150402435:ios:9314b049e2b69e096512b6',
    messagingSenderId: '976150402435',
    projectId: 'invoicegeneratordatabase-fdd48',
    storageBucket: 'invoicegeneratordatabase-fdd48.appspot.com',
    iosBundleId: 'com.example.invoiceGen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkxKMozOmASOXI6bC3sRon19wpxLTpFw4',
    appId: '1:976150402435:ios:2e48ba75eb20ede76512b6',
    messagingSenderId: '976150402435',
    projectId: 'invoicegeneratordatabase-fdd48',
    storageBucket: 'invoicegeneratordatabase-fdd48.appspot.com',
    iosBundleId: 'com.example.invoiceGen.RunnerTests',
  );
}
